analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: false
model:
  IsGraNoise: true
  P_gra_sel: 0.9
  P_sel: 0.9
  P_sel_onehot: 0.95
  SamSe: false
  Trans_layer_num: 2
  __doc__: "Config object.\n\n    Config objects are intended to hold all of the hyperparameters\
    \ associated with\n    a wandb run and are saved with the run object when `wandb.init`\
    \ is called.\n\n    We recommend setting `wandb.config` once at the top of your\
    \ training experiment or\n    setting the config as a parameter to init, ie. `wandb.init(config=my_config_dict)`\n\
    \n    You can create a file called `config-defaults.yaml`, and it will automatically\
    \ be\n    loaded into `wandb.config`. See https://docs.wandb.com/guides/track/config#file-based-configs.\n\
    \n    You can also load a config YAML file with your custom name and pass the\
    \ filename\n    into `wandb.init(config=\"special_config.yaml\")`.\n    See https://docs.wandb.com/guides/track/config#file-based-configs.\n\
    \n    Examples:\n        Basic usage\n        ```\n        wandb.config.epochs\
    \ = 4\n        wandb.init()\n        for x in range(wandb.config.epochs):\n  \
    \          # train\n        ```\n\n        Using wandb.init to set config\n  \
    \      ```\n        wandb.init(config={\"epochs\": 4, \"batch_size\": 32})\n \
    \       for x in range(wandb.config.epochs):\n            # train\n        ```\n\
    \n        Nested configs\n        ```\n        wandb.config['train']['epochs']\
    \ = 4\n        wandb.init()\n        for x in range(wandb.config['train']['epochs']):\n\
    \            # train\n        ```\n\n        Using absl flags\n        ```\n \
    \       flags.DEFINE_string(\"model\", None, \"model to run\")  # name, default,\
    \ help\n        wandb.config.update(flags.FLAGS)  # adds all absl flags to config\n\
    \        ```\n\n        Argparse flags\n        ```python\n        wandb.init()\n\
    \        wandb.config.epochs = 4\n\n        parser = argparse.ArgumentParser()\n\
    \        parser.add_argument(\n            \"-b\",\n            \"--batch-size\"\
    ,\n            type=int,\n            default=8,\n            metavar=\"N\",\n\
    \            help=\"input batch size for training (default: 8)\",\n        )\n\
    \        args = parser.parse_args()\n        wandb.config.update(args)\n     \
    \   ```\n\n        Using TensorFlow flags (deprecated in tensorflow v2)\n    \
    \    ```python\n        flags = tf.app.flags\n        flags.DEFINE_string(\"data_dir\"\
    , \"/tmp/data\")\n        flags.DEFINE_integer(\"batch_size\", 128, \"Batch size.\"\
    )\n        wandb.config.update(flags.FLAGS)  # adds all of the tensorflow flags\
    \ to config\n        ```\n    "
  _name: wandb.config
  act: F.relu
  dropout: 0.9
  dropout_att: 0.4
  input_layer: false
  method: rncgln
  n_heads: 8
  n_hidden: 32
  n_layer: 4
  norm_info: null
  order: 4
  output_layer: false
  r1: 0.001
  random_aug_feature: 0.4
  tau: 1
  trans_dim: 128
training:
  criterion: metric
  lr: 0.01
  n_epochs: 500
  patience: null
  warmup_num: 100
  weight_decay: 0.001
