analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  dropout: 0.43725705670085113
  input_layer: false
  method: gcn
  n_hidden: 64
  n_layer: 2
  norm_info: null
  output_layer: false
training:
  criterion: metric
  lr: 0.05
  n_epochs: 200
  patience: null
  weight_decay: 0.001
