analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  act: F.relu
  alpha: 0.0
  alpha1: 0.1
  alpha2: 0.1
  alpha3: 1
  beta: 10
  delta: 0.0
  dropout: 0.7
  gamma: 0.9
  input_layer: false
  method: r2lp
  n_hidden: 128
  n_layer: 1
  norm_func_id: 1
  norm_info: null
  norm_layers: 2
  orders: 1
  orders_func_id: 2
  output_layer: false
  pre_select: 0.2
training:
  criterion: metric
  lr: 0.02
  n_epochs: 200
  n_epochs_lp: 10
  patience: null
  pre_select: 0.5
  pre_unknown: 0.5
  weight_decay: 1e-07
