analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  dropout: 0.3
  method: gat
  mlp_layers: 1
  n_hidden: 64
  n_layer: 4
  train_eps: true
training:
  criterion: metric
  lr: 0.01
  n_epochs: 200
  patience: null
  weight_decay: 1e-05
