analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  T: 2
  _name: wandb.config
  act: F.relu
  alpha: 0.6
  beta: 1
  dropout: 0.3
  input_layer: false
  method: crgnn
  n_hidden: 16
  n_layer: 1
  noise_rate_init: 0.1
  norm_info: null
  output_layer: false
  p: 0.8
  tau: 0.5
training:
  criterion: metric
  lr: 0.05
  n_epochs: 200
  patience: null
  weight_decay: 0.05
