analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  act: F.relu
  alpha: 0.1
  beta: 1
  dropout: 0.7
  input_layer: false
  method: sce
  n_hidden: 64
  n_layer: 2
  norm_info: null
  output_layer: false
training:
  criterion: metric
  lr: 0.01
  n_epochs: 500
  patience: null
  weight_decay: 0.01
