analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  dropout: 0.3
  method: dgnn
  mlp_layers: 1
  n_hidden: 64
  n_layer: 2
  train_eps: true
training:
  criterion: metric
  lr: 0.01
  n_epochs: 300
  n_pre_epochs: 300
  patience: null
  weight_decay: 0.05
