analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  act: F.relu
  alpha: 100
  beta: 0.1
  dropout: 0.3
  input_layer: false
  method: apl
  n_hidden: 32
  n_layer: 4
  norm_info: null
  output_layer: false
training:
  criterion: metric
  lr: 0.1
  n_epochs: 500
  patience: null
  weight_decay: 5e-05
