analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  act: F.relu
  dropout: 0.3
  emb_batch_size: 128
  emb_context_size: 10
  emb_dim: 128
  emb_num_negative_samples: 1
  emb_num_workers: 1
  emb_p: 1.0
  emb_q: 1.0
  emb_walk_length: 20
  emb_walks_per_node: 10
  input_layer: false
  lam: 0.2
  method: cp
  n_cluster: 8
  n_hidden: 128
  n_layer: 2
  norm_info: null
  output_layer: false
training:
  criterion: metric
  emb_epochs: 100
  lr: 0.01
  n_epochs: 200
  patience: null
  weight_decay: 0.01
