analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  act: F.relu
  adjust_lr: 1
  co_lambda: 0.1
  dropout: 0.5
  exponent: 1
  forget_rate: 0.2
  input_layer: false
  method: jocor
  n_hidden: 128
  n_layer: 1
  norm_info: null
  num_gradual: 10
  output_layer: false
training:
  criterion: metric
  lr: 0.05
  n_epochs: 200
  patience: null
  weight_decay: 0.1
