analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  dropout: 0.23945318282590922
  input_layer: false
  method: gcn
  n_hidden: 128
  n_layer: 4
  norm_info: null
  output_layer: false
training:
  criterion: metric
  lr: 0.1
  n_epochs: 200
  patience: null
  weight_decay: 0.0001
