analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  dropout: 0.9
  method: sage
  n_hidden: 128
  n_layer: 1
training:
  criterion: metric
  lr: 0.01
  n_epochs: 200
  patience: null
  weight_decay: 5e-05
