analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  _name: wandb.config
  dropout: 0.1
  method: sage
  n_hidden: 32
  n_layer: 2
training:
  criterion: metric
  lr: 0.05
  n_epochs: 200
  patience: null
  weight_decay: 0.05
